import { RHYDB_WASM_ENABLED } from '../config';
import type { LocalRhyDBClient } from './localRhyDBClient';
import { withBase } from './paths';
import type { RhyDBInfo } from './rhydbInfo';

// Preprocessing inputs generated by scripts/prepare-example-data.mjs.
const DATASET_DIRECTORY = '/example-data/sars-cov-2-1000';
const CONFIG_FILENAME = 'preprocessing_config.yaml';
const INPUT_FILENAMES = [
    'data.ndjson.zst',
    'database_config.yaml',
    'reference_genomes.json',
    'lineage_definitions.yaml',
];

export const TUTORIAL_DATA_URL = withBase(`${DATASET_DIRECTORY}/${INPUT_FILENAMES[0]}`);

export type TutorialDatabaseState =
    | { status: 'unavailable' }
    | { status: 'idle' }
    | { status: 'loading'; message: string }
    | { status: 'ready'; client: LocalRhyDBClient; info: RhyDBInfo }
    | { status: 'error'; message: string };

// One database per browser tab, shared by every tutorial island on the page and kept out of React
// state so that it survives navigation between the loader and the consoles that query it.
let state: TutorialDatabaseState = supported() ? { status: 'idle' } : { status: 'unavailable' };
const listeners = new Set<() => void>();

export function subscribeToTutorialDatabase(listener: () => void) {
    listeners.add(listener);
    return () => listeners.delete(listener);
}

export function getTutorialDatabaseState() {
    return state;
}

export async function loadTutorialDatabase() {
    if (state.status !== 'idle' && state.status !== 'error') return;
    publish({ status: 'loading', message: 'Downloading the dataset…' });

    const { LocalRhyDBClient } = await import('./localRhyDBClient');
    const client = new LocalRhyDBClient();
    try {
        const { validateRawBundle } = await import('./localRhyDBFiles');
        const [configFile, ...inputFiles] = await Promise.all(
            [CONFIG_FILENAME, ...INPUT_FILENAMES].map(downloadDatasetFile),
        );
        const bundle = await validateRawBundle(configFile, inputFiles);
        if (!bundle.ok) throw new Error(bundle.message);

        const info = await client.preprocess(bundle.normalizedConfig, bundle.files, (event) => {
            if (event.type === 'progress') publish({ status: 'loading', message: event.value.message });
        });
        publish({ status: 'ready', client, info });
    } catch (error) {
        client.dispose();
        publish({ status: 'error', message: error instanceof Error ? error.message : String(error) });
    }
}

async function downloadDatasetFile(filename: string) {
    const url = withBase(`${DATASET_DIRECTORY}/${filename}`);
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Could not download ${filename} (HTTP ${response.status}).`);
    return new File([await response.blob()], filename);
}

function supported() {
    return (
        RHYDB_WASM_ENABLED &&
        typeof window !== 'undefined' &&
        window.crossOriginIsolated === true &&
        typeof Worker !== 'undefined' &&
        'WebAssembly' in window
    );
}

function publish(next: TutorialDatabaseState) {
    state = next;
    for (const listener of listeners) listener();
}
