import { RHYDB_WASM_ENABLED } from '../config';
import type { LocalRhyDBClient } from './localRhyDBClient';
import { withBase } from './paths';

// Preprocessing inputs generated by scripts/prepare-example-data.mjs. The configuration references the
// other three by name, and RhyDB reads them from the directory it preprocesses in.
const DATASET_DIRECTORY = '/example-data/sars-cov-2-1000';
const CONFIG_FILENAME = 'preprocessing_config.yaml';
const NDJSON_FILENAME = 'data.ndjson.zst';
const INPUT_FILENAMES = [NDJSON_FILENAME, 'database_config.yaml', 'reference_genomes.json', 'lineage_definitions.yaml'];

// The dataset the tutorial offers for download, so that readers can inspect what they just indexed.
export const TUTORIAL_DATA_URL = withBase(`${DATASET_DIRECTORY}/${NDJSON_FILENAME}`);

export type TutorialDatabaseState =
    | { status: 'unavailable' }
    | { status: 'idle' }
    | { status: 'loading' }
    | { status: 'ready'; client: LocalRhyDBClient }
    | { status: 'error'; message: string };

// One database per browser tab, shared by every tutorial island on the page and kept out of React
// state so that it survives navigation between the loader and the consoles that query it.
let state: TutorialDatabaseState = supported() ? { status: 'idle' } : { status: 'unavailable' };
const listeners = new Set<() => void>();

export function subscribeToTutorialDatabase(listener: () => void) {
    listeners.add(listener);
    return () => listeners.delete(listener);
}

export function getTutorialDatabaseState() {
    return state;
}

export async function loadTutorialDatabase() {
    if (state.status !== 'idle' && state.status !== 'error') return;
    publish({ status: 'loading' });

    const { LocalRhyDBClient } = await import('./localRhyDBClient');
    const client = new LocalRhyDBClient();
    try {
        const [config, ...files] = await Promise.all([CONFIG_FILENAME, ...INPUT_FILENAMES].map(downloadDatasetFile));
        await client.preprocess(await config.text(), files);
        publish({ status: 'ready', client });
    } catch (error) {
        client.dispose();
        publish({ status: 'error', message: error instanceof Error ? error.message : String(error) });
    }
}

async function downloadDatasetFile(filename: string) {
    const response = await fetch(withBase(`${DATASET_DIRECTORY}/${filename}`));
    if (!response.ok) throw new Error(`Could not download ${filename} (HTTP ${response.status}).`);
    return new File([await response.blob()], filename);
}

// The tutorial page imports TUTORIAL_DATA_URL, so this module is also evaluated while the site is
// built, where there is no window to ask.
function supported() {
    return RHYDB_WASM_ENABLED && typeof window !== 'undefined' && window.crossOriginIsolated === true;
}

function publish(next: TutorialDatabaseState) {
    state = next;
    for (const listener of listeners) listener();
}
